//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gmc_v_2_0.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipes_data
    {
        public string recipe_data_id { get; set; }
        public Nullable<int> step_num { get; set; }
        public string step_time { get; set; }
        public Nullable<int> wafer_rotatior_val { get; set; }
        public Nullable<int> wafer_rotatior_acc { get; set; }
        public string rinse_arm_disp { get; set; }
        public string rinse_arm_speed { get; set; }
        public string rinse_arm_start_pos { get; set; }
        public string rinse_arm_end_pos { get; set; }
        public Nullable<int> rinse_arm_scan { get; set; }
        public string dev_arm_disp { get; set; }
        public string dev_arm_time { get; set; }
        public string dev_arm_speed { get; set; }
        public string dev_arm_start_pos { get; set; }
        public string dev_arm_end_pos { get; set; }
        public Nullable<int> dev_arm_scan { get; set; }
        public string auto_damp { get; set; }
        public string n2_dry { get; set; }
        public string wait_type { get; set; }
        public Nullable<int> recipe_info_id { get; set; }
    }
}
